openapi: 3.0.1
info:
  title: Interest Rate Determination
  description: Interest Rate Determination
  version: 1.0.0
servers:
  - url: /api/v1rate
paths:
  '/{duration}':
    get:
      tags:
        - All Messages
      operationId: getInterestRateByDuration
      parameters:
        - $ref: '#/components/parameters/Duration'
      responses:
        '200':
          description: >-
            Determines the interest rate (nominal and effective) based on the
            duration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InterestRate'
components:
  schemas:
    InterestRate:
      type: object
      description: >-
        Determines the interest rate (nominal and effective) based on the
        duration
  parameters:
    Duration:
      name: duration
      in: path
      required: true
      schema:
        type: integer
