schemaVersion: /v1/apiSchema.schema.json
comments: []
creationTs: '1619181876202'
creator: Namrata Gupta
creatorId: 9cc2a3c7-4108-4270-84c3-4d45a8c793b2
type: object
allOfLinks:
  - /api/credit/schema/CreditApplication
properties:
  - name: accepted
    required: false
    schema:
      type: boolean
